package rc.unesp.br.cgen;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import java.util.Optional;
import java.util.concurrent.ThreadLocalRandom;

@Controller
public class HomeController {
    @PersistenceUnit
    private EntityManagerFactory emf;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CodigoRepository codigoRepository;

    @GetMapping("/")
    public String greetings(Model model) {

        Codigo codigo = new Codigo();
        long codigoCount = codigoRepository.count();
        model.addAttribute("codigo", "Sem códigos registrados");

        if (codigoCount > 0) {
            long randomId = ThreadLocalRandom.current().nextLong(1,  codigoCount);
            Optional isPresent;
            do {
                isPresent = codigoRepository.findById((int) randomId);
            } while(!isPresent.isPresent());
            codigo = (Codigo) isPresent.get();

            model.addAttribute("codigo", codigo.getTexto());
        }

        return "home";
    }

    @GetMapping("/get")
    public @ResponseBody Iterable<Codigo> getCode() {
        return codigoRepository.findAll();
    }
}
